-- AddNetworkString
util.AddNetworkString(BoringFPS_CONFIG.NetVar.StartClientTurn)
util.AddNetworkString(BoringFPS_CONFIG.NetVar.StopClientTurn)
util.AddNetworkString(BoringFPS_CONFIG.NetVar.PlayClientSound)
util.AddNetworkString(BoringFPS_CONFIG.NetVar.StopPlayClientSound)